# Generated by Django 5.2.11 on 2026-02-10 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('PAN', 'PAN'), ('AADHAAR', 'Aadhaar'), ('GST', 'GST'), ('FSSAI', 'FSSAI'), ('MSME', 'MSME')], max_length=20)),
                ('doc_number', models.CharField(blank=True, max_length=80)),
                ('holder_name', models.CharField(blank=True, max_length=200)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Invalid'), ('ERROR', 'Error')], default='ERROR', max_length=20)),
                ('api_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
